# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170522_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
