# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_tag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count_answers',
            field=models.IntegerField(default=0),
        ),
    ]
