# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20170523_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
    ]
