# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_remove_question_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='admin@mail.ru', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='login',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
